# Generated by Django 5.1.5 on 2025-01-27 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0003_customer_password'),
        ('PurchaseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='CustomerApp.customer'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, editable=False, max_digits=10),
            preserve_default=False,
        ),
    ]
