# Generated by Django 5.1.5 on 2025-01-28 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseApp', '0002_purchase_customer_purchase_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='date',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='discount',
        ),
    ]
