# Generated by Django 5.1.5 on 2025-01-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='roll',
            field=models.IntegerField(default=0),
        ),
    ]
